SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE VIEW [dbo].[vwCRMLoad_Account_Custom_Update]
AS
SELECT  
	 z.[crm_id] Id
	, b.SSID_Winner SSB_CRMSYSTEM_SSID_Winner__c
	, b.DimCustIDs SSB_CRMSYSTEM_DimCustomerID__c
	, LEFT(b.TM_IDs,255) SSB_CRMSYSTEM_SSID_TM__c
	, b.AccountID SSB_CRMSYSTEM_TM_Account_ID__c
	, b.SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c
	, b.SSB_CRMSYSTEM_Last_Donation_Date__c
	, ISNULL(b.SSB_CRMSYSTEM_Donor_Warning__c,0)  SSB_CRMSYSTEM_Donor_Warning__c
	, b.SSB_CRMSYSTEM_Total_Priority_Points__c
	, ISNULL(b.SSB_CRMSYSTEM_Football_STH__c,0) SSB_CRMSYSTEM_Football_STH__c
	, ISNULL(b.SSB_CRMSYSTEM_Football_Rookie__c,0)  SSB_CRMSYSTEM_Football_Rookie__c
	, ISNULL(b.SSB_CRMSYSTEM_Football_Partial__c,0)  SSB_CRMSYSTEM_Football_Partial__c
	, ISNULL(b.SSB_CRMSYSTEM_Mens_Basketball_STH__c,0)  SSB_CRMSYSTEM_Mens_Basketball_STH__c
	, ISNULL(b.SSB_CRMSYSTEM_Mens_Basketball_Rookie__c,0) SSB_CRMSYSTEM_Mens_Basketball_Rookie__c
	, ISNULL(b.SSB_CRMSYSTEM_Mens_Basketball_Partial__c,0) SSB_CRMSYSTEM_Mens_Basketball_Partial__c
	, ISNULL(b.SSB_CRMSYSTEM_CLA_CC1116_ConcertProspect__c,0) SSB_CRMSYSTEM_CLA_CC1116_ConcertProspect__c
	, ISNULL(b.SSB_CRMSYSTEM_CLA_CC11_16_Suite_Prospect__c,0) SSB_CRMSYSTEM_CLA_CC11_16_Suite_Prospect__c
	, ISNULL(b.SSB_CRMSYSTEM_CLA_CC11_16_Group_Buyer__c,0) SSB_CRMSYSTEM_CLA_CC11_16_Group_Buyer__c
	, ISNULL(b.SSB_CRMSYSTEM_CLA_CC11_16_Premium_Buyer__c,0) SSB_CRMSYSTEM_CLA_CC11_16_Premium_Buyer__c
	,b.SSB_CRMSYSTEM_CLA_CC11_16_Total_Spend__c
	, b.SSB_CRMSYSTEM_CY_Donation_Level__c
	, b.SSB_CRMSYSTEM_CY_Donation_Amount__c
	, b.SSB_CRMSYSTEM_CY_Donation_Upsell__c
	, b.SSB_CRMSYSTEM_Consecutive_Years__c	
	, b.SSB_CRMSYSTEM_Millenium_ID__c	
	, b.SSB_CRMSYSTEM_Phone_Home__c	
	, b.SSB_CRMSYSTEM_Phone_Cell__c
	, z.IsBusinessAccount SSB_CRMSYSTEM_CorporateBuyer_Flag__c

	--,'01241000000aNVAAA2' RecordTypeId
FROM dbo.[vwCRMLoad_Account_Std_Prep] a
INNER JOIN dbo.[Account_Custom] b ON [a].[SSB_CRMSYSTEM_ACCT_ID__c] = b.[SSB_CRMSYSTEM_ACCT_ID]
INNER JOIN dbo.Account z ON a.[SSB_CRMSYSTEM_ACCT_ID__c] = z.[SSB_CRMSYSTEM_ACCT_ID]
LEFT JOIN  prodcopy.vw_Account c ON z.[crm_id] = c.ID
WHERE z.[SSB_CRMSYSTEM_ACCT_ID] <> z.[crm_id]
AND  (HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST(  b.SSID_Winner AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_SSID_Winner__c AS VARCHAR(MAX)))),'')) 
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.DimCustIDs AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST(  c.SSB_CRMSYSTEM_DimCustomerID__c AS VARCHAR(MAX)))),'')) 
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( LEFT(b.TM_IDs,255) AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_SSID_TM__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.AccountID AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_TM_Account_ID__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Last_Donation_Date__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Last_Donation_Date__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Donor_Warning__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Donor_Warning__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Total_Priority_Points__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Total_Priority_Points__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Football_STH__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Football_STH__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Football_Rookie__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Football_Rookie__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Football_Partial__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Football_Partial__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Mens_Basketball_STH__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Mens_Basketball_STH__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Mens_Basketball_Rookie__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Mens_Basketball_Rookie__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Mens_Basketball_Partial__c AS VARCHAR(MAX)))),0) )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Mens_Basketball_Partial__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_CY_Donation_Level__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CY_Donation_Level__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_CY_Donation_Amount__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CY_Donation_Amount__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_CY_Donation_Upsell__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CY_Donation_Upsell__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Consecutive_Years__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Consecutive_Years__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Millenium_ID__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Millenium_ID__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Phone_Home__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Phone_Home__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_Phone_Cell__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_Phone_Cell__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_CLA_CC1116_ConcertProspect__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CLA_CC1116_ConcertProspect__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( ISNULL(b.SSB_CRMSYSTEM_CLA_CC11_16_Group_Buyer__c,0) AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CLA_CC11_16_Group_Buyer__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( ISNULL(b.SSB_CRMSYSTEM_CLA_CC11_16_Premium_Buyer__c,0) AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CLA_CC11_16_Premium_Buyer__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( ISNULL(b.SSB_CRMSYSTEM_CLA_CC11_16_Suite_Prospect__c,0) AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CLA_CC11_16_Suite_Prospect__c AS VARCHAR(MAX)))),''))
	OR HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( b.SSB_CRMSYSTEM_CLA_CC11_16_Total_Spend__c AS VARCHAR(MAX)))),'') )  <> HASHBYTES('SHA2_256',ISNULL(LTRIM(RTRIM(CAST( c.SSB_CRMSYSTEM_CLA_CC11_16_Total_Spend__c AS VARCHAR(MAX)))),''))
	)





GO
