SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create PROC [dbo].[sp_CRMProcess_UpdateGUIDs_ProdCopy_Contact]
AS

UPDATE A
SET SSB_CRMSYSTEM_ACCT_ID__c = b.SSB_CRMSYSTEM_ACCT_ID,
	SSB_CRMSYSTEM_CONTACT_ID__c = b.SSB_CRMSYSTEM_CONTACT_ID
FROM ProdCopy.Contact A
INNER JOIN dbo.vwDimCustomer_ModAcctId b
	 ON b.SSID = a.id
WHERE a.SSB_CRMSYSTEM_CONTACT_ID__c IS NULL OR a.SSB_CRMSYSTEM_CONTACT_ID__c <> b.[SSB_CRMSYSTEM_CONTACT_ID]


GO
