CREATE TABLE [dbo].[Contact_Custom]
(
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSID_Winner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonTicket_Years] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Account] [bit] NULL,
[MDMProcess_UpdatedDate] [datetime] NULL CONSTRAINT [DF_Contact_Custom_MDMProcess_UpdatedDate] DEFAULT (getdate()),
[SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c] [date] NULL,
[SSB_CRMSYSTEM_Last_Donation_Date__c] [date] NULL,
[SSB_CRMSYSTEM_Donor_Warning__c] [bit] NULL,
[SSB_CRMSYSTEM_Total_Priority_Points__c] [decimal] (7, 2) NULL,
[SSB_CRMSYSTEM_Football_STH__c] [bit] NULL,
[SSB_CRMSYSTEM_Football_Rookie__c] [bit] NULL,
[SSB_CRMSYSTEM_Football_Partial__c] [bit] NULL,
[SSB_CRMSYSTEM_Mens_Basketball_STH__c] [bit] NULL,
[SSB_CRMSYSTEM_Mens_Basketball_Rookie__c] [bit] NULL,
[SSB_CRMSYSTEM_Mens_Basketball_Partial__c] [bit] NULL,
[SSB_CRMSYSTEM_CY_Donation_Level__c] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_CY_Donation_Amount__c] [decimal] (10, 2) NULL,
[SSB_CRMSYSTEM_CY_Donation_Upsell__c] [decimal] (10, 2) NULL,
[SSB_CRMSYSTEM_Company_Name__c] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_CLA_CC11_16_Group_Buyer__c] [bit] NULL,
[SSB_CRMSYSTEM_CLA_CC11_16_Premium_Buyer__c] [bit] NULL,
[SSB_CRMSYSTEM_CLA_CC11_16_Total_Spend__c] [decimal] (15, 2) NULL,
[SSB_CRMSYSTEM_CLA_CC11_16_Suite_Prospect__c] [bit] NULL,
[SSB_CRMSYSTEM_Consecutive_Years__c] [decimal] (16, 2) NULL,
[SSB_CRMSYSTEM_Millenium_ID__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_CLA_CC1116_ConcertProspect__c] [bit] NULL,
[household_income__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Personicx_Cluster__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Net_Worth__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Football_Priority__c] [int] NULL,
[SSB_CRMSYSTEM_Basketball_Priority__c] [int] NULL,
[SSB_CRMSYSTEM_PresenceofChildren__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Football_Priority_Date__c] [date] NULL,
[SSB_CRMSYSTEM_First_Donation_Date__c] [date] NULL,
[SSB_CRMSYSTEM_Student_Class_Standing__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Student_Completed_Hours__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Student_Semester_Hours__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Student_College__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Student_Housing__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Account_Type__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Group_Buyer__c] [date] NULL,
[SSB_Mens_Basketball_Seat_Selection] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_Football_First_Seat_Selection] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_Football_Second_Seat_Selection] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_Football_Parking_Selection] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_Womens_Basketball_Times] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_Market] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [dbo].[Contact_Custom] ADD CONSTRAINT [PK_Contact_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_CONTACT_ID])
GO
